enabled = true 
rbl_must = true 
syslog_identifier = ['postfix/smtpd']
action = 'ban'
re = [
  '^lost connection after AUTH from unknown\[{{.Ipv4}}\]$'
  , '^connect from \S+\[{{.Ipv4}}\]$'
] 
testdata = [
  'lost connection after AUTH from unknown[185.234.219.253]'
  , 'connect from staticline-31-182-44-246.toya.net.pl[31.182.44.246]'
]
